title : CIRCAE
description: 'Somos el Centro de Investigaci贸n en Rob贸tica, Control
              y Automatizaci贸n Electr贸nica - CIRCAE'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist, jekyll-paginate]
permalink: /:year/:month/:title.html
